### ISSUE TITLE
Undeclared variable in robotsim package

### ISSUE THREAD

**Issue by joeka36** [wanweiwei07/pymanipulator#1]
In the file nxtik.py in line 177, armjntsiter is an undeclared variable. I think it is referencing armjointsiter from line 143. Both should be converted to numpy float array to do the calculation in line 177.

**Comment by wanweiwei07** [comment]
Thank you very much!
It has been corrected.

--
Weiwei Wan,
Associate Professor,
School/Graduate School of Engineering Science,
Osaka University
